const fs = require("fs");
const path = require("path");

const parser = [
'export interface ParsedMonth { month: string; balances: Record<string, number>; }',
'export interface ClientParseResult { success: boolean; bank?: string; holder?: string; months_data: ParsedMonth[]; abb_6m: number; abb_1y: number; error?: string; }',
'const ML: Record<string, number> = {jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11};',
'const MN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];',
'',
'function detectBank(t: string): string {',
'  const l = t.toLowerCase();',
'  if (l.includes("post payments") || l.includes("ippb")) return "India Post Payments Bank";',
'  if (l.includes("state bank") || l.includes("sbi")) return "State Bank of India";',
'  if (l.includes("hdfc")) return "HDFC Bank"; if (l.includes("icici")) return "ICICI Bank";',
'  if (l.includes("axis")) return "Axis Bank"; if (l.includes("kotak")) return "Kotak Mahindra Bank";',
'  if (l.includes("punjab") || l.includes("pnb")) return "Punjab National Bank";',
'  if (l.includes("baroda")) return "Bank of Baroda"; if (l.includes("canara")) return "Canara Bank";',
'  if (l.includes("union bank")) return "Union Bank of India";',
'  return "Bank";',
'}',
'',
'function detectHolder(t: string): string {',
'  const skip = /account|statement|branch|address|period|registered|customer|mobile|ifsc|micr|details|transaction|office|a\\/c/i;',
'  for (const l of t.split(/\\n/).map(s => s.trim()).filter(s => s.length > 2 && s.length < 60)) {',
'    if (skip.test(l) || /^\\d/.test(l)) continue;',
'    if (/^[A-Z][A-Za-z.\\s]{2,45}$/.test(l)) return l;',
'  }',
'  return "";',
'}',
'',
'function parseDate(s: string): { day: number; month: number; year: number } | null {',
'  // DD-MM-YYYY or DD/MM/YYYY',
'  let m = s.match(/(\\d{1,2})[\\/\\-](\\d{1,2})[\\/\\-](\\d{4})/);',
'  if (m) return { day: parseInt(m[1]), month: parseInt(m[2]) - 1, year: parseInt(m[3]) };',
'  // DD-Mon-YYYY',
'  m = s.match(/(\\d{1,2})[\\/\\-\\s](Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*[\\/\\-\\s](\\d{4})/i);',
'  if (m) return { day: parseInt(m[1]), month: ML[m[2].substring(0, 3).toLowerCase()], year: parseInt(m[3]) };',
'  return null;',
'}',
'',
'// KEY FIX: Extract balance = LAST number with decimal point on the line',
'// In bank statements: ... WITHDRAWAL  DEPOSIT  BALANCE  Cr./Dr.',
'// The balance is always the final number with 2 decimal places',
'function extractBalance(line: string): number | null {',
'  // Find all numbers with 2 decimal places (e.g. 17891.60, 7429.60)',
'  const matches = line.match(/\\d[\\d,]*\\.\\d{2}/g);',
'  if (!matches || matches.length === 0) return null;',
'  // The LAST such number is the running/closing balance',
'  const last = matches[matches.length - 1].replace(/,/g, "");',
'  const val = parseFloat(last);',
'  return isNaN(val) ? null : val;',
'}',
'',
'export function parseBankStatementClient(',
'  text: string,',
'  sampleDays: number[],',
'  maxMonths: number',
'): ClientParseResult {',
'  const bank = detectBank(text);',
'  const holder = detectHolder(text);',
'',
'  // Step 1: Parse every transaction line -> { date, balance }',
'  interface Entry { day: number; month: number; year: number; balance: number; dateKey: string; monthKey: string; }',
'  const allEntries: Entry[] = [];',
'',
'  for (const rawLine of text.split(/\\n/)) {',
'    const line = rawLine.trim();',
'    if (!line) continue;',
'    const d = parseDate(line);',
'    if (!d) continue;',
'    const bal = extractBalance(line);',
'    if (bal === null) continue;',
'    allEntries.push({',
'      ...d,',
'      balance: bal,',
'      dateKey: String(d.day).padStart(2, "0") + "-" + String(d.month + 1).padStart(2, "0") + "-" + d.year,',
'      monthKey: MN[d.month] + " " + d.year,',
'    });',
'  }',
'',
'  if (allEntries.length < 3) {',
'    return {',
'      success: false,',
'      error: "Could not extract enough transactions from statement. Found " + allEntries.length + " entries.",',
'      bank, holder, months_data: [], abb_6m: 0, abb_1y: 0,',
'    };',
'  }',
'',
'  // Step 2: Group ALL entries by date key (DD-MM-YYYY)',
'  // For each date, the LAST entry has the closing balance for that day',
'  const dateBalances = new Map<string, number>();',
'  for (const e of allEntries) {',
'    dateBalances.set(e.dateKey, e.balance); // overwrites -> keeps last',
'  }',
'',
'  // Step 3: Group dates by month',
'  const monthDates = new Map<string, { day: number; balance: number }[]>();',
'  for (const [dateKey, balance] of dateBalances) {',
'    const entry = allEntries.find(e => e.dateKey === dateKey);',
'    if (!entry) continue;',
'    if (!monthDates.has(entry.monthKey)) monthDates.set(entry.monthKey, []);',
'    monthDates.get(entry.monthKey)!.push({ day: entry.day, balance });',
'  }',
'',
'  // Step 4: Sort months chronologically',
'  const sortedMonths = Array.from(monthDates.keys()).sort((a, b) => {',
'    const [am, ay] = a.split(" ");',
'    const [bm, by] = b.split(" ");',
'    if (ay !== by) return parseInt(ay) - parseInt(by);',
'    return ML[am.toLowerCase()] - ML[bm.toLowerCase()];',
'  });',
'',
'  // Take last N months (up to maxMonths, but also limit to available full months)',
'  const targetMonths = sortedMonths.slice(-maxMonths);',
'',
'  // Step 5: For each month, extract balances on exact target days',
'  const months_data: ParsedMonth[] = targetMonths.map(mk => {',
'    const dates = monthDates.get(mk)!;',
'    const balances: Record<string, number> = {};',
'    for (const targetDay of sampleDays) {',
'      // Find the exact day or the closest day BEFORE the target',
'      // (use the last available balance on or before the target date)',
'      let bestBal: number | null = null;',
'      let bestDay = -1;',
'      for (const d of dates) {',
'        if (d.day <= targetDay && d.day > bestDay) {',
'          bestDay = d.day;',
'          bestBal = d.balance;',
'        }',
'      }',
'      // Also check if there is an exact match or day after (within 1 day)',
'      if (bestBal === null) {',
'        for (const d of dates) {',
'          if (d.day >= targetDay && d.day <= targetDay + 1 && (bestBal === null || d.day < bestDay)) {',
'            bestBal = d.balance;',
'            bestDay = d.day;',
'          }',
'        }',
'      }',
'      if (bestBal !== null) {',
'        balances[String(targetDay)] = bestBal;',
'      }',
'    }',
'    return { month: mk, balances };',
'  });',
'',
'  // Step 6: Calculate ABB',
'  function calcABB(data: ParsedMonth[]): number {',
'    let totalSum = 0;',
'    let totalCount = 0;',
'    for (const m of data) {',
'      const vals = Object.values(m.balances).filter(v => v > 0);',
'      if (vals.length > 0) {',
'        totalSum += vals.reduce((a, b) => a + b, 0) / vals.length;',
'        totalCount++;',
'      }',
'    }',
'    return totalCount > 0 ? totalSum / totalCount : 0;',
'  }',
'',
'  return {',
'    success: true,',
'    bank,',
'    holder,',
'    months_data,',
'    abb_6m: calcABB(months_data.slice(-6)),',
'    abb_1y: calcABB(months_data),',
'  };',
'}',
].join('\n');

fs.writeFileSync(path.join(process.cwd(), "src", "lib", "parseBankClient.ts"), parser, "utf8");
console.log("Updated: src/lib/parseBankClient.ts");
console.log("Key fix: Balance = LAST number with 2 decimal places per line");
console.log("Key fix: For each date, keeps LAST transaction entry (closing balance)");