var fs = require('fs');
var o = [];
function w() { for (var i = 0; i < arguments.length; i++) o.push(arguments[i]); }
var F = 'D:\\mahajan-finance-suite-main cashflow added\\src\\pages\\AccountingServices.tsx';

w('');
w('function ServiceForm({ service, index }: { service: AccountingService; index: number }) {');
w('  const [form, setForm] = useState<Record<string, string>>({});');
w('  const [loading, setLoading] = useState(false);');
w('  const [open, setOpen] = useState(false);');
w('  const [uploadedDocs, setUploadedDocs] = useState<Record<string, File>>({});');
w('  const [submitted, setSubmitted] = useState(false);');
w('');
w('  const u = (k: string, v: string) => setForm(p => ({ ...p, [k]: v }));');
w('  const handleDocChange = useCallback((docName: string) => (file: File | null) => {');
w('    setUploadedDocs(p => { if (file) return { ...p, [docName]: file }; var n = { ...p }; delete n[docName]; return n; });');
w('  }, []);');
w('');
w('  const handleSubmit = async () => {');
w('    if (!form.name || !form.mobile) { toast.error("Name and Mobile are required"); return; }');
w('    setLoading(true);');
w('    try {');
w('      var docUrls: string[] = [], docNames: string[] = [];');
w('      for (var dk of Object.keys(uploadedDocs)) {');
w('        var dr = await uploadDocsToStorage(uploadedDocs[dk], "accounting", form.name);');
w('        if (dr) { docUrls.push(dr.url); docNames.push(dk); }');
w('      }');
w('      var sess = (await supabase.auth.getSession()).data.session;');
w('      var res = await fetch("/functions/v1/send-enquiry-email", {');
w('        method: "POST",');
w('        headers: { "Content-Type": "application/json", Authorization: "Bearer " + (sess ? sess.access_token : "") },');
w('        body: JSON.stringify({');
w('          serviceName: service.title, customerName: form.name, customerMobile: form.mobile,');
w('          details: { Email: form.email || "N/A", City: form.city || "N/A" },');
w('          documentUrls: docUrls,');
w('        }),');
w('      });');
w('      if (res.ok) {');
w('        setSubmitted(true);');
w('        toast.success("Enquiry submitted!");');
w('        var msg = "New Accounting Enquiry\\nService: " + service.title + "\\nName: " + form.name + "\\nMobile: " + form.mobile + (docNames.length ? "\\nDocs: " + docNames.join(", ") : "");');
w('        await fetch("https://api.fonnte.com/send", { method: "POST", headers: { Authorization: "ghoLfHFvEMbc3TWc11MU" }, body: JSON.stringify({ target: "919730540215", message: msg, countryCode: "91" }) });');
w('      } else { toast.error("Submission failed"); }');
w('    } catch (e) { toast.error("Error: " + (e as any).message); }');
w('    setLoading(false);');
w('  };');
w('');
w('  if (submitted) return (');
w('    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 rounded-xl p-8 text-center">');
w('      <CheckCircle2 size={48} className="mx-auto text-emerald-500 mb-3" />');
w('      <h3 className="text-xl font-bold text-emerald-800 dark:text-emerald-200">Enquiry Submitted!</h3>');
w('      <p className="text-sm text-emerald-600 dark:text-emerald-400 mt-2">We will contact you within 24 hours.</p>');
w('    </motion.div>');
w('  );');
w('');
w('  var inputClass = "w-full px-3 py-2 rounded-lg border border-border bg-background text-sm focus:ring-2 focus:ring-primary/30 focus:border-primary outline-none transition-all";');
w('  var Icon = service.icon;');
w('');
w('  return (');
w('    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.05 }} className="bg-card rounded-xl border border-border overflow-hidden shadow-sm">');
w('      <button onClick={() => setOpen(!open)} className="w-full flex items-center gap-4 p-5 text-left hover:bg-muted/30 transition-colors">');
w('        <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0"><Icon size={24} className="text-primary" /></div>');
w('        <div className="flex-1 min-w-0">');
w('          <h3 className="font-bold text-foreground">{service.title}</h3>');
w('          <p className="text-xs text-muted-foreground mt-0.5 line-clamp-1">{service.description}</p>');
w('          <div className="flex flex-wrap gap-1.5 mt-2">{service.badges.map((b, i) => <Badge key={i} variant={b.variant}>{b.label}</Badge>)}</div>');
w('        </div>');
w('        <div className="text-right shrink-0 hidden sm:block">');
w('          <p className="text-sm font-bold text-primary">{service.price}</p>');
w('          <p className="text-xs text-muted-foreground flex items-center justify-end gap-1 mt-0.5"><Clock size={12} />{service.timeline}</p>');
w('        </div>');
w('        {open ? <ChevronUp size={20} className="text-muted-foreground shrink-0" /> : <ChevronDown size={20} className="text-muted-foreground shrink-0" />}');
w('      </button>');
w('      <AnimatePresence>{open && (');
w('        <motion.div initial={{ height: 0 }} animate={{ height: "auto" }} exit={{ height: 0 }} className="overflow-hidden">');
w('          <div className="px-5 pb-5 space-y-4 border-t border-border/50 pt-4">');
w('            <InfoBox>Fill in the details below and our team will get back to you within 24 hours.</InfoBox>');
w('            <div className="space-y-3">');
w('              {service.fields.map((f) => (');
w('                <div key={f.key}>');
w('                  <label className="block text-sm font-medium text-foreground mb-1">{f.label}{f.required && <span className="text-destructive ml-0.5">*</span>}{f.hint && <span className="text-muted-foreground font-normal ml-1">({f.hint})</span>}</label>');
w('                  {f.type === "select" ? (');
w('                    <select value={form[f.key] || ""} onChange={(e) => u(f.key, e.target.value)} className={inputClass}>');
w('                      <option value="">Select {f.label}</option>');
w('                      {f.options?.map((opt) => <option key={opt} value={opt}>{opt}</option>)}');
w('                    </select>');
w('                  ) : f.type === "textarea" ? (');
w('                    <textarea value={form[f.key] || ""} onChange={(e) => u(f.key, e.target.value)} className={inputClass + " min-h-[80px] resize-y"} placeholder={f.label} />');
w('                  ) : (');
w('                    <input type={f.type || "text"} value={form[f.key] || ""} onChange={(e) => u(f.key, e.target.value)} className={inputClass} placeholder={f.label} />');
w('                  )}');
w('                </div>');
w('              ))}');
w('            </div>');
w('            <div className="space-y-2">');
w('              <h4 className="text-sm font-semibold flex items-center gap-2"><FileText size={16} />Required Documents</h4>');
w('              {service.docs.map((d) => (');
w('                <DocumentUpload key={d.name} docName={d.name} file={uploadedDocs[d.name] || null} onFile={handleDocChange(d.name)} />');
w('              ))}');
w('            </div>');
w('            <button onClick={handleSubmit} disabled={loading} className="w-full flex items-center justify-center gap-2 py-3 rounded-lg bg-primary text-primary-foreground font-bold hover:bg-primary/90 disabled:opacity-50 transition-all">');
w('              {loading ? <><Circle size={16} className="animate-spin" /> Submitting...</> : <><Send size={16} /> Submit Enquiry</>}');
w('            </button>');
w('          </div>');
w('        </motion.div>');
w('      )}</AnimatePresence>');
w('    </motion.div>');
w('  );');
w('}');
w('');
w('export default function AccountingServices() {');
w('  return (');
w('    <>');
w('      <section className="py-14 sm:py-20 bg-gradient-to-br from-primary via-primary/90 to-primary/80 text-primary-foreground relative overflow-hidden">');
w('        <div className="absolute inset-0 bg-[url(/grid.svg)] opacity-10" />');
w('        <div className="container max-w-3xl text-center relative z-10">');
w('          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}>');
w('            <h1 className="text-3xl sm:text-4xl font-extrabold font-display tracking-tight">Accounting & Registration Services</h1>');
w('            <p className="mt-3 text-primary-foreground/80 text-sm sm:text-base max-w-xl mx-auto">Professional accounting, tax filing, and business registration services by certified experts. Affordable pricing with doorstep service.</p>');
w('          </motion.div>');
w('        </div>');
w('      </section>');
w('      <section className="py-8 bg-background border-b border-border/40">');
w('        <div className="container max-w-3xl flex flex-wrap justify-center gap-6 sm:gap-10">');
w('          {[[ShieldCheck,"500+ Filed"],[Users,"300+ Clients"],[CalendarDays,"Since 2018"],[IndianRupee,"Affordable"]].map(([Ic,lbl],i) => (');
w('            <div key={i} className="flex items-center gap-2 text-sm text-muted-foreground"><Ic size={18} className="text-primary" /><span className="font-medium">{lbl}</span></div>');
w('          ))}');
w('        </div>');
w('      </section>');
w('      <section className="py-8 bg-muted/20">');
w('        <div className="container max-w-3xl text-center">');
w('          <h2 className="text-lg font-bold font-display mb-4">Our Services</h2>');
w('          <div className="flex flex-wrap justify-center gap-3 mt-6">');
w('            {["ITR Filing","GST Returns","Company Registration","LLP Registration","FPC Registration","Trust Registration","Project Reports"].map((s) => (');
w('              <span key={s} className="px-3 py-1 rounded-full bg-primary-foreground/10 text-primary-foreground/80 text-xs font-medium">{s}</span>');
w('            ))}');
w('          </div>');
w('        </div>');
w('      </section>');
w('      <section className="py-10 sm:py-14 bg-background">');
w('        <div className="container max-w-3xl space-y-4">');
w('          {accountingServices.map((s, i) => (');
w('            <ServiceForm key={s.key} service={s} index={i} />');
w('          ))}');
w('        </div>');
w('      </section>');
w('      <section className="py-6 bg-muted/30 border-t border-border/40">');
w('        <div className="container max-w-3xl text-center">');
w('          <p className="text-xs text-muted-foreground leading-relaxed">All information is based on official government sources (incometax.gov.in, gst.gov.in, mca.gov.in) as of June 2025. Tax laws and regulations are subject to change. Fees shown are indicative and may vary by state and service provider. Always verify with official portals before filing.</p>');
w('        </div>');
w('      </section>');
w('    </>');
w('  );');
w('}');

fs.appendFileSync(F, '\n' + o.join('\n'), 'utf8');
console.log('Part 2 done: ' + o.length + ' lines appended');
