# === SCRIPT 10: Professional TabDashboard with Enhanced Cards ===

$projectRoot = $PSScriptRoot
if (-not $projectRoot) { $projectRoot = Get-Location }
$componentPath = Join-Path $projectRoot "src\components\tracker\TabDashboard.tsx"

$lines = @(
'import { useEffect, useState } from "react";',
'import { acc, fmtINR } from "@/lib/accounting";',
'import { TrendingUp, TrendingDown, Wallet, Users, Receipt, FileWarning, ArrowUpRight, ArrowDownRight, IndianRupee, Clock } from "lucide-react";',
'',
'const TabDashboard = ({ userId }: { userId: string }) => {',
'  const [stats, setStats] = useState({',
'    incomeMTD: 0, expenseMTD: 0, profit: 0, receivables: 0, payables: 0,',
'    cash: 0, parties: 0, overdue: 0, invoiceCount: 0, expenseCount: 0,',
'  });',
'  const [loading, setLoading] = useState(true);',
'',
'  useEffect(() => {',
'    const load = async () => {',
'      const monthStart = new Date(); monthStart.setDate(1);',
'      const monthStartISO = monthStart.toISOString().split("T")[0];',
'',
'      const [invMTD, expMTD, invAll, partyCount, payIn, payOut] = await Promise.all([',
'        acc("acc_invoices").select("total,paid,due_date,status,doc_type").eq("user_id", userId).gte("invoice_date", monthStartISO),',
'        acc("acc_expenses").select("amount,gst").eq("user_id", userId).gte("expense_date", monthStartISO),',
'        acc("acc_invoices").select("total,paid,due_date,status,doc_type").eq("user_id", userId).neq("status", "cancelled"),',
'        acc("acc_parties").select("id", { count: "exact", head: true }).eq("user_id", userId),',
'        acc("acc_payments").select("amount").eq("user_id", userId).eq("direction", "in"),',
'        acc("acc_payments").select("amount").eq("user_id", userId).eq("direction", "out"),',
'      ]);',
'',
'      const sumPaidInvoices = (invMTD.data || [])',
'        .filter((i: any) => i.doc_type === "invoice")',
'        .reduce((s: number, i: any) => s + Number(i.total || 0), 0);',
'      const expenseMTDVal = (expMTD.data || []).reduce((s: number, e: any) => s + Number(e.amount || 0) + Number(e.gst || 0), 0);',
'      const billsMTD = (invMTD.data || [])',
'        .filter((i: any) => i.doc_type === "bill")',
'        .reduce((s: number, i: any) => s + Number(i.total || 0), 0);',
'',
'      let receivables = 0, payables = 0, overdue = 0;',
'      const today = new Date().toISOString().split("T")[0];',
'      for (const i of invAll.data || []) {',
'        const due = Number(i.total || 0) - Number(i.paid || 0);',
'        if (due <= 0) continue;',
'        if (i.doc_type === "invoice") receivables += due; else payables += due;',
'        if (i.due_date && i.due_date < today) overdue++;',
'      }',
'      const cash = (payIn.data || []).reduce((s: number, p: any) => s + Number(p.amount), 0)',
'                 - (payOut.data || []).reduce((s: number, p: any) => s + Number(p.amount), 0);',
'',
'      setStats({',
'        incomeMTD: sumPaidInvoices,',
'        expenseMTD: expenseMTDVal + billsMTD,',
'        profit: sumPaidInvoices - expenseMTDVal - billsMTD,',
'        receivables, payables, cash,',
'        parties: partyCount.count || 0,',
'        overdue,',
'        invoiceCount: (invAll.data || []).filter((i: any) => i.doc_type === "invoice").length,',
'        expenseCount: (expMTD.data || []).length,',
'      });',
'      setLoading(false);',
'    };',
'    load();',
'  }, [userId]);',
'',
'  if (loading) return <div className="text-center py-10 animate-pulse text-muted-foreground">Loading Dashboard...</div>;',
'',
'  return (',
'    <div className="space-y-6">',
'      {/* Greeting */}',
'      <div>',
'        <h3 className="text-xl font-extrabold font-display">Dashboard</h3>',
'        <p className="text-xs text-muted-foreground mt-0.5">Your business at a glance</p>',
'      </div>',
'',
'      {/* MTD Section */}',
'      <div>',
'        <h4 className="text-xs font-bold text-muted-foreground mb-3 uppercase tracking-wider">This Month</h4>',
'        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">',
'          <div className="bg-gradient-to-br from-emerald-500 to-green-600 rounded-2xl p-5 text-white shadow-lg shadow-emerald-500/20">',
'            <div className="flex justify-between items-start">',
'              <ArrowUpRight size={24} className="opacity-80" />',
'              <span className="text-xs bg-white/20 px-2 py-0.5 rounded-full font-bold">INCOME</span>',
'            </div>',
'            <p className="text-3xl font-extrabold mt-3">{fmtINR(stats.incomeMTD)}</p>',
'            <p className="text-sm opacity-80 mt-1">Monthly Revenue</p>',
'          </div>',
'          <div className="bg-gradient-to-br from-red-500 to-rose-600 rounded-2xl p-5 text-white shadow-lg shadow-red-500/20">',
'            <div className="flex justify-between items-start">',
'              <ArrowDownRight size={24} className="opacity-80" />',
'              <span className="text-xs bg-white/20 px-2 py-0.5 rounded-full font-bold">EXPENSE</span>',
'            </div>',
'            <p className="text-3xl font-extrabold mt-3">{fmtINR(stats.expenseMTD)}</p>',
'            <p className="text-sm opacity-80 mt-1">Monthly Spending</p>',
'          </div>',
'          <div className={"bg-gradient-to-br rounded-2xl p-5 text-white shadow-lg " + (stats.profit >= 0 ? "from-blue-500 to-indigo-600 shadow-blue-500/20" : "from-red-600 to-rose-700 shadow-red-500/20")}>',
'            <div className="flex justify-between items-start">',
'              <Wallet size={24} className="opacity-80" />',
'              <span className="text-xs bg-white/20 px-2 py-0.5 rounded-full font-bold">{stats.profit >= 0 ? "PROFIT" : "LOSS"}</span>',
'            </div>',
'            <p className="text-3xl font-extrabold mt-3">{fmtINR(Math.abs(stats.profit))}</p>',
'            <p className="text-sm opacity-80 mt-1">{stats.profit >= 0 ? "Net Profit" : "Net Loss"}</p>',
'          </div>',
'        </div>',
'      </div>',
'',
'      {/* Overview Section */}',
'      <div>',
'        <h4 className="text-xs font-bold text-muted-foreground mb-3 uppercase tracking-wider">Business Overview</h4>',
'        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">',
'          <div className="bg-card rounded-2xl border-2 border-border p-5 hover:border-blue-300 hover:shadow-md hover:shadow-blue-500/10 transition-all">',
'            <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center mb-3"><Receipt size={20} className="text-blue-600" /></div>',
'            <p className="text-2xl font-extrabold tabular-nums">{fmtINR(stats.receivables)}</p>',
'            <p className="text-xs text-muted-foreground mt-1">Receivables (to receive)</p>',
'          </div>',
'          <div className="bg-card rounded-2xl border-2 border-border p-5 hover:border-amber-300 hover:shadow-md hover:shadow-amber-500/10 transition-all">',
'            <div className="w-10 h-10 rounded-xl bg-amber-100 flex items-center justify-center mb-3"><IndianRupee size={20} className="text-amber-600" /></div>',
'            <p className="text-2xl font-extrabold tabular-nums">{fmtINR(stats.payables)}</p>',
'            <p className="text-xs text-muted-foreground mt-1">Payables (to pay)</p>',
'          </div>',
'          <div className="bg-card rounded-2xl border-2 border-border p-5 hover:border-emerald-300 hover:shadow-md hover:shadow-emerald-500/10 transition-all">',
'            <div className="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center mb-3"><Wallet size={20} className="text-emerald-600" /></div>',
'            <p className="text-2xl font-extrabold tabular-nums">{fmtINR(stats.cash)}</p>',
'            <p className="text-xs text-muted-foreground mt-1">Net Cash Position</p>',
'          </div>',
'          <div className="bg-card rounded-2xl border-2 border-border p-5 hover:border-purple-300 hover:shadow-md hover:shadow-purple-500/10 transition-all">',
'            <div className="w-10 h-10 rounded-xl bg-purple-100 flex items-center justify-center mb-3"><Users size={20} className="text-purple-600" /></div>',
'            <p className="text-2xl font-extrabold">{stats.parties}</p>',
'            <p className="text-xs text-muted-foreground mt-1">Total Parties</p>',
'          </div>',
'          <div className="bg-card rounded-2xl border-2 border-border p-5 hover:border-indigo-300 hover:shadow-md hover:shadow-indigo-500/10 transition-all">',
'            <div className="w-10 h-10 rounded-xl bg-indigo-100 flex items-center justify-center mb-3"><Receipt size={20} className="text-indigo-600" /></div>',
'            <p className="text-2xl font-extrabold">{stats.invoiceCount}</p>',
'            <p className="text-xs text-muted-foreground mt-1">Total Invoices</p>',
'          </div>',
'          <div className="bg-card rounded-2xl border-2 border-border p-5 hover:border-red-300 hover:shadow-md hover:shadow-red-500/10 transition-all">',
'            <div className="w-10 h-10 rounded-xl bg-red-100 flex items-center justify-center mb-3"><Clock size={20} className="text-red-600" /></div>',
'            <p className="text-2xl font-extrabold">{stats.overdue}</p>',
'            <p className="text-xs text-muted-foreground mt-1">Overdue Invoices</p>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'  );',
'};',
'',
'export default TabDashboard;',
)

[System.IO.File]::WriteAllText($componentPath, ($lines -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "=== TabDashboard.tsx UPDATED ===" -ForegroundColor Green
Write-Host "  + Gradient hero cards for Income/Expense/Profit"
Write-Host "  + Icon badges in overview cards"
Write-Host "  + Hover effects on all cards"
Write-Host "  + Loading state"
Write-Host "  + Professional layout with sections"