# === SCRIPT 7: Professional UI for TabItems with Bulk Add ===

$projectRoot = $PSScriptRoot
if (-not $projectRoot) { $projectRoot = Get-Location }
$componentPath = Join-Path $projectRoot "src\components\tracker\TabItems.tsx"

$lines = @(
'import { useEffect, useState } from "react";',
'import { acc, fmtINR } from "@/lib/accounting";',
'import { toast } from "sonner";',
'import { Plus, Trash2, Package, Upload, X, Search } from "lucide-react";',
'',
'const inputClass = "w-full px-3 py-2 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary";',
'',
'const TabItems = ({ userId }: { userId: string }) => {',
'  const [list, setList] = useState<any[]>([]);',
'  const [show, setShow] = useState(false);',
'  const [search, setSearch] = useState("");',
'  const [bulkMode, setBulkMode] = useState(false);',
'  const [bulkText, setBulkText] = useState("");',
'  const [bulkPreview, setBulkPreview] = useState<any[]>([]);',
'  const [form, setForm] = useState({ name: "", sku: "", hsn: "", unit: "pcs", sale_price: 0, purchase_price: 0, gst_rate: 18, stock_qty: 0 });',
'',
'  const load = async () => {',
'    const { data } = await acc("acc_items").select("*").eq("user_id", userId).order("created_at", { ascending: false });',
'    setList(data || []);',
'  };',
'  useEffect(() => { load(); }, [userId]);',
'',
'  const save = async () => {',
'    if (!form.name) { toast.error("Item name required"); return; }',
'    const { error } = await acc("acc_items").insert({ ...form, user_id: userId, name: form.name.toUpperCase() });',
'    if (error) { toast.error(error.message); return; }',
'    toast.success("Item added");',
'    setForm({ name: "", sku: "", hsn: "", unit: "pcs", sale_price: 0, purchase_price: 0, gst_rate: 18, stock_qty: 0 });',
'    setShow(false); load();',
'  };',
'  const remove = async (id: string) => {',
'    if (!confirm("Delete this item?")) return;',
'    await acc("acc_items").delete().eq("id", id);',
'    toast.success("Deleted"); load();',
'  };',
'',
'  // Bulk Import',
'  const parseBulk = () => {',
'    const rows = bulkText.trim().split("\\n").filter(l => l.trim());',
'    const parsed: any[] = [];',
'    for (const row of rows) {',
'      const cols = row.split("\\t").map(c => c.trim());',
'      if (cols.length >= 1 && cols[0]) {',
'        parsed.push({ name: cols[0], sku: cols[1] || "", hsn: cols[2] || "", unit: cols[3] || "pcs", sale: Number(cols[4]) || 0, purchase: Number(cols[5]) || 0, gst: Number(cols[6]) || 18, stock: Number(cols[7]) || 0 });',
'      }',
'    }',
'    setBulkPreview(parsed);',
'  };',
'  const saveBulk = async () => {',
'    if (bulkPreview.length === 0) return;',
'    const rows = bulkPreview.map(b => ({',
'      user_id: userId, name: b.name.toUpperCase(), sku: b.sku.toUpperCase(),',
'      hsn: b.hsn, unit: b.unit, sale_price: b.sale, purchase_price: b.purchase,',
'      gst_rate: b.gst, stock_qty: b.stock,',
'    }));',
'    const { error } = await acc("acc_items").insert(rows);',
'    if (error) { toast.error(error.message); return; }',
'    toast.success(`${bulkPreview.length} items added!`);',
'    setBulkMode(false); setBulkText(""); setBulkPreview([]); load();',
'  };',
'',
'  const stockValue = list.reduce((s, i) => s + Number(i.stock_qty) * Number(i.purchase_price), 0);',
'  const totalItems = list.reduce((s, i) => s + Number(i.stock_qty), 0);',
'  const filtered = list.filter(i => !search || i.name.toLowerCase().includes(search.toLowerCase()) || (i.sku || "").toLowerCase().includes(search.toLowerCase()));',
'',
'  return (',
'    <div className="space-y-5">',
'      {/* Header */}',
'      <div className="flex flex-wrap items-center justify-between gap-3">',
'        <div>',
'          <h3 className="text-xl font-extrabold font-display">Items & Services</h3>',
'          <p className="text-xs text-muted-foreground mt-0.5">{list.length} items | {totalItems} total stock units</p>',
'        </div>',
'        <div className="flex flex-wrap gap-2">',
'          <button onClick={() => { setBulkMode(!bulkMode); setShow(false); }} className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-bold transition-all ${bulkMode ? "bg-violet-500 text-white shadow-lg shadow-violet-500/30" : "bg-violet-50 text-violet-700 border border-violet-200 hover:bg-violet-100"}`}>',
'            <Upload size={14} /> Bulk Add',
'          </button>',
'          <button onClick={() => { setShow(!show); setBulkMode(false); }} className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-bold transition-all ${show ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30" : "bg-accent text-accent-foreground hover:scale-105"}`}>',
'            <Plus size={14} /> Add Item',
'          </button>',
'        </div>',
'      </div>',
'',
'      {/* Quick Stats */}',
'      <div className="grid grid-cols-2 gap-3">',
'        <div className="bg-gradient-to-br from-indigo-500 to-blue-600 rounded-xl p-4 text-white">',
'          <Package size={18} className="mb-1 opacity-80" />',
'          <p className="text-2xl font-extrabold">{list.length}</p>',
'          <p className="text-xs opacity-80">Total Items</p>',
'        </div>',
'        <div className="bg-gradient-to-br from-emerald-500 to-green-600 rounded-xl p-4 text-white">',
'          <Package size={18} className="mb-1 opacity-80" />',
'          <p className="text-2xl font-extrabold">{fmtINR(stockValue)}</p>',
'          <p className="text-xs opacity-80">Stock Value</p>',
'        </div>',
'      </div>',
'',
'      {/* Search */}',
'      {list.length > 0 && (',
'        <div className="relative">',
'          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />',
'          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by name or SKU..." className={`${inputClass} pl-9`} />',
'        </div>',
'      )}',
'',
'      {/* Add Form */}',
'      {show && (',
'        <div className="bg-card rounded-2xl border-2 border-golden/30 p-5 space-y-4 shadow-lg shadow-golden/5 animate-in fade-in slide-in-from-top-2 duration-300">',
'          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">',
'            <input value={form.name} onChange={e => setForm(p => ({ ...p, name: e.target.value.toUpperCase() }))} placeholder="ITEM NAME *" className={`${inputClass} uppercase`} />',
'            <input value={form.sku} onChange={e => setForm(p => ({ ...p, sku: e.target.value.toUpperCase() }))} placeholder="SKU" className={`${inputClass} uppercase`} />',
'            <input value={form.hsn} onChange={e => setForm(p => ({ ...p, hsn: e.target.value }))} placeholder="HSN/SAC" className={inputClass} />',
'            <input value={form.unit} onChange={e => setForm(p => ({ ...p, unit: e.target.value }))} placeholder="Unit" className={inputClass} />',
'            <input type="number" value={form.sale_price} onChange={e => setForm(p => ({ ...p, sale_price: Number(e.target.value) }))} placeholder="Sale price" className={inputClass} />',
'            <input type="number" value={form.purchase_price} onChange={e => setForm(p => ({ ...p, purchase_price: Number(e.target.value) }))} placeholder="Purchase price" className={inputClass} />',
'            <input type="number" value={form.gst_rate} onChange={e => setForm(p => ({ ...p, gst_rate: Number(e.target.value) }))} placeholder="GST %" className={inputClass} />',
'            <input type="number" value={form.stock_qty} onChange={e => setForm(p => ({ ...p, stock_qty: Number(e.target.value) }))} placeholder="Opening stock" className={inputClass} />',
'          </div>',
'          <button onClick={save} className="btn-accent w-full !py-2.5 rounded-lg font-bold">Save Item</button>',
'        </div>',
'      )}',
'',
'      {/* Bulk Import */}',
'      {bulkMode && (',
'        <div className="bg-gradient-to-r from-violet-50 to-purple-50 border-2 border-violet-300 rounded-2xl p-5 space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">',
'          <div className="flex items-center justify-between">',
'            <div className="flex items-center gap-2">',
'              <div className="w-8 h-8 rounded-lg bg-violet-500 flex items-center justify-center"><Upload size={16} className="text-white" /></div>',
'              <div><h4 className="font-extrabold text-violet-900">Bulk Item Import</h4><p className="text-xs text-violet-700">Tab-separated: Name, SKU, HSN, Unit, SalePrice, PurchasePrice, GST%, Stock</p></div>',
'            </div>',
'            <button onClick={() => { setBulkMode(false); setBulkText(""); setBulkPreview([]); }} className="p-1 rounded hover:bg-violet-200"><X size={16} /></button>',
'          </div>',
'          <textarea value={bulkText} onChange={e => setBulkText(e.target.value)} placeholder={`WIDGET A\\tSKU001\\t8471\\tpcs\\t100\\t60\\t18\\t50\nSERVICE B\\t\\t9983\\thour\\t500\\t\\t18\\t0`} rows={4} className={`${inputClass} font-mono text-xs`} />',
'          <div className="flex gap-2">',
'            <button onClick={parseBulk} className="px-4 py-2 rounded-lg bg-violet-500 text-white font-bold text-sm hover:bg-violet-600 transition-colors">Preview ({bulkText.trim().split("\\n").filter(l=>l.trim()).length} rows)</button>',
'            {bulkPreview.length > 0 && <button onClick={saveBulk} className="px-4 py-2 rounded-lg bg-gradient-to-r from-violet-600 to-purple-600 text-white font-bold text-sm hover:shadow-lg transition-all">Import {bulkPreview.length} Items</button>}',
'          </div>',
'          {bulkPreview.length > 0 && (',
'            <div className="overflow-x-auto rounded-lg border max-h-48 overflow-y-auto">',
'              <table className="w-full text-xs"><thead className="bg-violet-100 sticky top-0"><tr>',
'                <th className="px-3 py-2 text-left">Name</th><th className="px-3 py-2">SKU</th>',
'                <th className="px-3 py-2 text-right">Sale</th><th className="px-3 py-2">GST%</th>',
'                <th className="px-3 py-2 text-right">Stock</th>',
'              '</tr></thead><tbody>',
'                {bulkPreview.map((b, i) => <tr key={i} className="border-b"><td className="px-3 py-1.5 font-medium">{b.name}</td><td className="px-3 py-1.5 text-center">{b.sku || "-"}</td><td className="px-3 py-1.5 text-right font-bold">{fmtINR(b.sale)}</td><td className="px-3 py-1.5 text-center">{b.gst}%</td><td className="px-3 py-1.5 text-right">{b.stock} {b.unit}</td></tr>)}',
'              '</tbody></table>',
'            </div>',
'          )}',
'        </div>',
'      )}',
'',
'      {/* Items List */}',
'      <div className="bg-card rounded-2xl border-2 border-golden/20 overflow-hidden shadow-sm">',
'        {list.length === 0 ? (',
'          <div className="p-12 text-center">',
'            <div className="w-16 h-16 rounded-full bg-muted/50 flex items-center justify-center mx-auto mb-3"><Package size={28} className="text-muted-foreground" /></div>',
'            <p className="text-muted-foreground text-sm">No items yet.</p>',
'            <p className="text-muted-foreground text-xs mt-1">Add your products or services</p>',
'          </div>',
'        ) : (',
'          <div className="overflow-x-auto">',
'            <table className="w-full text-sm">',
'              <thead className="bg-gradient-to-r from-muted/80 to-muted/40"><tr>',
'                <th className="px-3 py-2.5 text-left text-xs font-bold text-muted-foreground">Item</th>',
'                <th className="px-3 py-2.5 text-left text-xs font-bold text-muted-foreground">HSN</th>',
'                <th className="px-3 py-2.5 text-right text-xs font-bold text-muted-foreground">Sale</th>',
'                <th className="px-3 py-2.5 text-right text-xs font-bold text-muted-foreground">GST</th>',
'                <th className="px-3 py-2.5 text-right text-xs font-bold text-muted-foreground">Stock</th>',
'                <th className="px-3 py-2.5 w-10"></th>',
'              '</tr></thead>',
'              <tbody>',
'                {filtered.length === 0 && <tr><td colSpan={6} className="p-6 text-center text-muted-foreground text-sm">No matching items.</td></tr>}',
'                {filtered.map(i => (',
'                  <tr key={i.id} className="border-b border-border/30 hover:bg-muted/20 transition-colors">',
'                    <td className="px-3 py-2.5 font-bold">{i.name} <span className="text-xs text-muted-foreground font-normal">{i.sku ? `(${i.sku})` : ""}</span></td>',
'                    <td className="px-3 py-2.5 text-xs font-mono text-muted-foreground">{i.hsn || "---"}</td>',
'                    <td className="px-3 py-2.5 text-right tabular-nums font-bold">{fmtINR(i.sale_price)}</td>',
'                    <td className="px-3 py-2.5 text-right tabular-nums">{i.gst_rate}%</td>',
'                    <td className="px-3 py-2.5 text-right tabular-nums"><span className={Number(i.stock_qty) <= 5 ? "text-red-600 font-bold" : ""}>{i.stock_qty} {i.unit}</span></td>',
'                    <td className="px-3 py-2.5 text-right">',
'                      <button onClick={() => remove(i.id)} className="p-1.5 rounded-lg hover:bg-red-50 text-red-500 transition-colors"><Trash2 size={14} /></button>',
'                    </td>',
'                  </tr>',
'                ))}',
'              '</tbody>',
'            </table>',
'          </div>',
'        )}',
'      </div>',
'    </div>',
'  );',
'};',
'',
'export default TabItems;',
)

[System.IO.File]::WriteAllText($componentPath, ($lines -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "=== TabItems.tsx UPDATED ===" -ForegroundColor Green
Write-Host "  + Bulk import (tab-separated)"
Write-Host "  + Search bar"
Write-Host "  + Stats cards (items count + stock value)"
Write-Host "  + Low stock warning (red when <= 5)"
Write-Host "  + Professional UI (empty state, gradients)"