# === SCRIPT 4: Enhanced TabInvoices ===
# Features: Quick Bill mode, Bulk Import, Stats cards, Professional UI, Search/Filter

$projectRoot = $PSScriptRoot
if (-not $projectRoot) { $projectRoot = Get-Location }
$componentPath = Join-Path $projectRoot "src\components\tracker\TabInvoices.tsx"

$lines = @(
'import { useEffect, useMemo, useState } from "react";',
'import { acc, fmtINR, todayISO } from "@/lib/accounting";',
'import { toast } from "sonner";',
'import { Plus, Trash2, FileDown, Share2, Search, Zap, Upload, X, FileText, IndianRupee, Clock, CheckCircle } from "lucide-react";',
'import jsPDF from "jspdf";',
'',
'const inputClass = "w-full px-3 py-2 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary";',
'',
'interface LineItem { description: string; hsn: string; qty: number; rate: number; gst_rate: number; }',
'',
'const TabInvoices = ({ userId, docType }: { userId: string; docType: "invoice" | "bill" }) => {',
'  const [list, setList] = useState<any[]>([]);',
'  const [parties, setParties] = useState<any[]>([]);',
'  const [items, setItems] = useState<any[]>([]);',
'  const [business, setBusiness] = useState<any>(null);',
'  const [show, setShow] = useState(false);',
'  const [search, setSearch] = useState("");',
'  const [statusFilter, setStatusFilter] = useState("all");',
'  // Quick Bill mode',
'  const [quickBill, setQuickBill] = useState(false);',
'  const [qbParty, setQbParty] = useState("");',
'  const [qbItem, setQbItem] = useState("");',
'  const [qbQty, setQbQty] = useState(1);',
'  // Bulk mode',
'  const [bulkMode, setBulkMode] = useState(false);',
'  const [bulkText, setBulkText] = useState("");',
'  const [bulkPreview, setBulkPreview] = useState<any[]>([]);',
'  const [form, setForm] = useState({',
'    party_id: "", invoice_no: "", invoice_date: todayISO(), due_date: "",',
'    notes: "", discount: 0,',
'  });',
'  const [lines, setLines] = useState<LineItem[]>([{ description: "", hsn: "", qty: 1, rate: 0, gst_rate: 18 }]);',
'',
'  const load = async () => {',
'    const [invR, partyR, itemR, busR] = await Promise.all([',
'      acc("acc_invoices").select("*, acc_parties(name)").eq("user_id", userId).eq("doc_type", docType).order("invoice_date", { ascending: false }),',
'      acc("acc_parties").select("id,name,party_type").eq("user_id", userId),',
'      acc("acc_items").select("*").eq("user_id", userId),',
'      acc("acc_business").select("*").eq("user_id", userId).maybeSingle(),',
'    ]);',
'    setList(invR.data || []);',
'    setParties(partyR.data || []);',
'    setItems(itemR.data || []);',
'    setBusiness(busR.data);',
'    const prefix = busR.data?.invoice_prefix || (docType === "invoice" ? "INV" : "BILL");',
'    const nextNum = (invR.data?.length || 0) + 1;',
'    setForm(p => ({ ...p, invoice_no: `${prefix}-${String(nextNum).padStart(4, "0")}` }));',
'  };',
'  useEffect(() => { load(); /* eslint-disable-next-line */ }, [userId, docType]);',
'',
'  const totals = useMemo(() => {',
'    let subtotal = 0, tax = 0;',
'    for (const l of lines) {',
'      const amt = (l.qty || 0) * (l.rate || 0);',
'      subtotal += amt;',
'      tax += amt * (l.gst_rate || 0) / 100;',
'    }',
'    const total = subtotal + tax - (form.discount || 0);',
'    return { subtotal, tax, total };',
'  }, [lines, form.discount]);',
'',
'  const addLine = () => setLines(p => [...p, { description: "", hsn: "", qty: 1, rate: 0, gst_rate: 18 }]);',
'  const updateLine = (i: number, k: keyof LineItem, v: any) => setLines(p => p.map((l, idx) => idx === i ? { ...l, [k]: v } : l));',
'  const removeLine = (i: number) => setLines(p => p.length > 1 ? p.filter((_, idx) => idx !== i) : p);',
'  const fillFromItem = (i: number, itemId: string) => {',
'    const it = items.find(x => x.id === itemId);',
'    if (!it) return;',
'    updateLine(i, "description", it.name);',
'    updateLine(i, "hsn", it.hsn || "");',
'    updateLine(i, "rate", it.sale_price);',
'    updateLine(i, "gst_rate", it.gst_rate);',
'  };',
'',
'  const save = async () => {',
'    if (!form.party_id) { toast.error("Select a party"); return; }',
'    if (!lines.some(l => l.description)) { toast.error("Add at least one line item"); return; }',
'    const { data: inv, error } = await acc("acc_invoices").insert({',
'      user_id: userId, doc_type: docType,',
'      party_id: form.party_id, invoice_no: form.invoice_no,',
'      invoice_date: form.invoice_date, due_date: form.due_date || null,',
'      subtotal: totals.subtotal, tax_total: totals.tax, discount: form.discount,',
'      total: totals.total, paid: 0, status: "unpaid", notes: form.notes,',
'    }).select().single();',
'    if (error || !inv) { toast.error(error?.message || "Save failed"); return; }',
'    const lineRows = lines.filter(l => l.description).map(l => ({',
'      invoice_id: inv.id, user_id: userId,',
'      description: l.description, hsn: l.hsn,',
'      qty: l.qty, rate: l.rate, gst_rate: l.gst_rate,',
'      amount: l.qty * l.rate,',
'    }));',
'    await acc("acc_invoice_items").insert(lineRows);',
'    toast.success(`${docType === "invoice" ? "Invoice" : "Bill"} saved`);',
'    setShow(false); setLines([{ description: "", hsn: "", qty: 1, rate: 0, gst_rate: 18 }]);',
'    setForm(p => ({ ...p, party_id: "", notes: "", discount: 0 }));',
'    load();',
'  };',
'',
'  // Quick Bill',
'  const handleQuickBill = async () => {',
'    if (!qbParty) { toast.error("Select a party"); return; }',
'    const it = items.find(x => x.id === qbItem);',
'    if (!it) { toast.error("Select an item"); return; }',
'    if (qbQty <= 0) { toast.error("Enter valid quantity"); return; }',
'    const amt = it.sale_price * qbQty;',
'    const tax = amt * (it.gst_rate || 0) / 100;',
'    const total = amt + tax;',
'    const prefix = business?.invoice_prefix || "INV";',
'    const nextNum = (list.length || 0) + 1;',
'    const invNo = `${prefix}-${String(nextNum).padStart(4, "0")}`;',
'    const { data: inv, error } = await acc("acc_invoices").insert({',
'      user_id: userId, doc_type: docType, party_id: qbParty, invoice_no: invNo,',
'      invoice_date: todayISO(), due_date: "", subtotal: amt, tax_total: tax,',
'      discount: 0, total, paid: 0, status: "unpaid", notes: "Quick Bill",',
'    }).select().single();',
'    if (error || !inv) { toast.error(error?.message || "Quick bill failed"); return; }',
'    await acc("acc_invoice_items").insert({',
'      invoice_id: inv.id, user_id: userId, description: it.name, hsn: it.hsn || "",',
'      qty: qbQty, rate: it.sale_price, gst_rate: it.gst_rate, amount: amt,',
'    });',
'    toast.success("Quick Bill created!");',
'    setQbParty(""); setQbItem(""); setQbQty(1);',
'    load();',
'  };',
'',
'  // Bulk Import',
'  const parseBulk = () => {',
'    const rows = bulkText.trim().split("\\n").filter(l => l.trim());',
'    const parsed: any[] = [];',
'    for (const row of rows) {',
'      const cols = row.split("\\t").map(c => c.trim());',
'      if (cols.length >= 2) {',
'        parsed.push({ party: cols[0], item: cols[1], qty: Number(cols[2]) || 1, rate: Number(cols[3]) || 0, gst: Number(cols[4]) || 18, hsn: cols[5] || "" });',
'      }',
'    }',
'    setBulkPreview(parsed);',
'  };',
'  const saveBulk = async () => {',
'    if (bulkPreview.length === 0) return;',
'    let count = 0;',
'    const prefix = business?.invoice_prefix || "INV";',
'    let num = list.length + 1;',
'    for (const b of bulkPreview) {',
'      const party = parties.find(p => p.name.toUpperCase() === b.party.toUpperCase());',
'      if (!party) continue;',
'      const amt = b.rate * b.qty;',
'      const tax = amt * b.gst / 100;',
'      const invNo = `${prefix}-${String(num).padStart(4, "0")}`;',
'      const { data: inv } = await acc("acc_invoices").insert({',
'        user_id: userId, doc_type: docType, party_id: party.id, invoice_no: invNo,',
'        invoice_date: todayISO(), due_date: "", subtotal: amt, tax_total: tax,',
'        discount: 0, total: amt + tax, paid: 0, status: "unpaid", notes: "Bulk Import",',
'      }).select().single();',
'      if (inv) {',
'        await acc("acc_invoice_items").insert({',
'          invoice_id: inv.id, user_id: userId, description: b.item.toUpperCase(), hsn: b.hsn,',
'          qty: b.qty, rate: b.rate, gst_rate: b.gst, amount: amt,',
'        });',
'        count++; num++;',
'      }',
'    }',
'    toast.success(`${count} invoices created via bulk import`);',
'    setBulkMode(false); setBulkText(""); setBulkPreview([]); load();',
'  };',
'',
'  const recordPayment = async (inv: any) => {',
'    const amount = Number(prompt(`Amount received (max ${inv.total - inv.paid}):`, String(inv.total - inv.paid)));',
'    if (!amount || isNaN(amount)) return;',
'    const newPaid = Number(inv.paid) + amount;',
'    const status = newPaid >= Number(inv.total) ? "paid" : "partial";',
'    await acc("acc_invoices").update({ paid: newPaid, status }).eq("id", inv.id);',
'    await acc("acc_payments").insert({',
'      user_id: userId, party_id: inv.party_id, invoice_id: inv.id,',
'      direction: docType === "invoice" ? "in" : "out", mode: "cash",',
'      amount, pay_date: todayISO(),',
'    });',
'    toast.success("Payment recorded"); load();',
'  };',
'',
'  const remove = async (id: string) => {',
'    if (!confirm("Delete this invoice?")) return;',
'    await acc("acc_invoices").delete().eq("id", id);',
'    toast.success("Deleted"); load();',
'  };',
'',
'  const downloadPdf = async (inv: any) => {',
'    const { data: lineRows } = await acc("acc_invoice_items").select("*").eq("invoice_id", inv.id);',
'    const party = parties.find(p => p.id === inv.party_id);',
'    const pdf = new jsPDF();',
'    const biz = business || {};',
'    pdf.setFontSize(18); pdf.text(biz.business_name || "My Business", 14, 18);',
'    pdf.setFontSize(9); pdf.text(biz.address || "", 14, 24);',
'    pdf.text(`GSTIN: ${biz.gstin || "-"}  |  Ph: ${biz.phone || "-"}`, 14, 29);',
'    pdf.setFontSize(14); pdf.text(docType === "invoice" ? "TAX INVOICE" : "PURCHASE BILL", 150, 18);',
'    pdf.setFontSize(9);',
'    pdf.text(`No: ${inv.invoice_no}`, 150, 24);',
'    pdf.text(`Date: ${inv.invoice_date}`, 150, 29);',
'    pdf.text(`Due: ${inv.due_date || "-"}`, 150, 34);',
'    pdf.setFontSize(10); pdf.text(`${docType === "invoice" ? "Bill To" : "Vendor"}: ${party?.name || "-"}`, 14, 42);',
'    let y = 52;',
'    pdf.setFontSize(9);',
'    pdf.text("Description", 14, y); pdf.text("HSN", 90, y); pdf.text("Qty", 110, y);',
'    pdf.text("Rate", 130, y); pdf.text("GST%", 150, y); pdf.text("Amount", 175, y);',
'    pdf.line(14, y + 1, 196, y + 1); y += 6;',
'    for (const l of lineRows || []) {',
'      pdf.text(String(l.description).slice(0, 40), 14, y);',
'      pdf.text(String(l.hsn || ""), 90, y);',
'      pdf.text(String(l.qty), 110, y);',
'      pdf.text(String(l.rate), 130, y);',
'      pdf.text(String(l.gst_rate) + "%", 150, y);',
'      pdf.text(String(l.amount), 175, y);',
'      y += 6;',
'    }',
'    y += 4; pdf.line(120, y, 196, y); y += 6;',
'    pdf.text(`Subtotal: ${fmtINR(inv.subtotal)}`, 130, y); y += 5;',
'    pdf.text(`Tax: ${fmtINR(inv.tax_total)}`, 130, y); y += 5;',
'    pdf.text(`Discount: ${fmtINR(inv.discount)}`, 130, y); y += 5;',
'    pdf.setFontSize(11); pdf.text(`TOTAL: ${fmtINR(inv.total)}`, 130, y);',
'    pdf.save(`${inv.invoice_no}.pdf`);',
'  };',
'',
'  const sharePdf = (inv: any) => {',
'    const party = parties.find(p => p.id === inv.party_id);',
'    const msg = `Hi ${party?.name || ""}, sharing ${docType} ${inv.invoice_no} for ${fmtINR(inv.total)}. Thank you!`;',
'    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, "_blank");',
'  };',
'',
'  const filteredParties = parties.filter(p => docType === "invoice" ? p.party_type !== "vendor" : p.party_type !== "customer");',
'',
'  // Filtered list',
'  const filtered = list.filter(i => {',
'    if (statusFilter !== "all" && i.status !== statusFilter) return false;',
'    if (search && !(i.invoice_no || "").toLowerCase().includes(search.toLowerCase()) && !(i.acc_parties?.name || "").toLowerCase().includes(search.toLowerCase())) return false;',
'    return true;',
'  });',
'',
'  // Stats',
'  const totalAmount = list.reduce((s, i) => s + Number(i.total), 0);',
'  const totalPaid = list.reduce((s, i) => s + Number(i.paid), 0);',
'  const totalDue = totalAmount - totalPaid;',
'  const paidCount = list.filter(i => i.status === "paid").length;',
'  const overdueCount = list.filter(i => {',
'    if (i.status === "paid") return false;',
'    return i.due_date && i.due_date < new Date().toISOString().split("T")[0];',
'  }).length;',
'',
'  return (',
'    <div className="space-y-5">',
'      {/* Header */}',
'      <div className="flex flex-wrap justify-between items-center gap-3">',
'        <div>',
'          <h3 className="text-xl font-extrabold font-display">{docType === "invoice" ? "Sales Invoices" : "Purchase Bills"}</h3>',
'          <p className="text-xs text-muted-foreground mt-0.5">{list.length} total | {fmtINR(totalAmount)} gross</p>',
'        </div>',
'        <div className="flex flex-wrap gap-2">',
'          <button onClick={() => setQuickBill(!quickBill)} className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-bold transition-all ${quickBill ? "bg-amber-500 text-white shadow-lg shadow-amber-500/30" : "bg-amber-50 text-amber-700 border border-amber-200 hover:bg-amber-100"}`}>',
'            <Zap size={14} /> Quick Bill',
'          </button>',
'          <button onClick={() => { setBulkMode(!bulkMode); setShow(false); setQuickBill(false); }} className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-bold transition-all ${bulkMode ? "bg-violet-500 text-white shadow-lg shadow-violet-500/30" : "bg-violet-50 text-violet-700 border border-violet-200 hover:bg-violet-100"}`}>',
'            <Upload size={14} /> Bulk Import',
'          </button>',
'          <button onClick={() => { setShow(!show); setBulkMode(false); setQuickBill(false); }} className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-bold transition-all ${show ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30" : "bg-accent text-accent-foreground hover:scale-105"}`}>',
'            <Plus size={14} /> New {docType === "invoice" ? "Invoice" : "Bill"}',
'          </button>',
'        </div>',
'      </div>',
'',
'      {/* Stats Cards */}',
'      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">',
'        <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl p-4 text-white">',
'          <FileText size={18} className="mb-1 opacity-80" />',
'          <p className="text-2xl font-extrabold">{list.length}</p>',
'          <p className="text-xs opacity-80">Total</p>',
'        </div>',
'        <div className="bg-gradient-to-br from-emerald-500 to-emerald-600 rounded-xl p-4 text-white">',
'          <CheckCircle size={18} className="mb-1 opacity-80" />',
'          <p className="text-2xl font-extrabold">{paidCount}</p>',
'          <p className="text-xs opacity-80">Paid</p>',
'        </div>',
'        <div className="bg-gradient-to-br from-amber-500 to-orange-500 rounded-xl p-4 text-white">',
'          <IndianRupee size={18} className="mb-1 opacity-80" />',
'          <p className="text-2xl font-extrabold">{fmtINR(totalDue)}</p>',
'          <p className="text-xs opacity-80">Amount Due</p>',
'        </div>',
'        <div className="bg-gradient-to-br from-red-500 to-rose-600 rounded-xl p-4 text-white">',
'          <Clock size={18} className="mb-1 opacity-80" />',
'          <p className="text-2xl font-extrabold">{overdueCount}</p>',
'          <p className="text-xs opacity-80">Overdue</p>',
'        </div>',
'      </div>',
'',
'      {/* Quick Bill Panel */}',
'      {quickBill && (',
'        <div className="bg-gradient-to-r from-amber-50 to-orange-50 border-2 border-amber-300 rounded-2xl p-5 space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">',
'          <div className="flex items-center gap-2 mb-2">',
'            <div className="w-8 h-8 rounded-lg bg-amber-500 flex items-center justify-center"><Zap size={16} className="text-white" /></div>',
'            <div><h4 className="font-extrabold text-amber-900">Quick Bill</h4><p className="text-xs text-amber-700">Create invoice in 3 seconds</p></div>',
'          </div>',
'          <div className="grid grid-cols-1 md:grid-cols-4 gap-3">',
'            <select value={qbParty} onChange={e => setQbParty(e.target.value)} className={inputClass}>',
'              <option value="">Select Customer *</option>',
'              {filteredParties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}',
'            </select>',
'            <select value={qbItem} onChange={e => setQbItem(e.target.value)} className={inputClass}>',
'              <option value="">Select Item *</option>',
'              {items.map(it => <option key={it.id} value={it.id}>{it.name} - {fmtINR(it.sale_price)}</option>)}',
'            </select>',
'            <input type="number" value={qbQty} onChange={e => setQbQty(Number(e.target.value))} placeholder="Quantity" min="1" className={inputClass} />',
'            <button onClick={handleQuickBill} className="bg-gradient-to-r from-amber-500 to-orange-500 text-white font-extrabold rounded-lg hover:shadow-lg hover:shadow-amber-500/30 transition-all hover:scale-[1.02]">Create Bill</button>',
'          </div>',
'        </div>',
'      )}',
'',
'      {/* Bulk Import Panel */}',
'      {bulkMode && (',
'        <div className="bg-gradient-to-r from-violet-50 to-purple-50 border-2 border-violet-300 rounded-2xl p-5 space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">',
'          <div className="flex items-center justify-between">',
'            <div className="flex items-center gap-2">',
'              <div className="w-8 h-8 rounded-lg bg-violet-500 flex items-center justify-center"><Upload size={16} className="text-white" /></div>',
'              <div><h4 className="font-extrabold text-violet-900">Bulk Invoice Import</h4><p className="text-xs text-violet-700">Paste tab-separated: PartyName, Item, Qty, Rate, GST%, HSN</p></div>',
'            </div>',
'            <button onClick={() => { setBulkMode(false); setBulkText(""); setBulkPreview([]); }} className="p-1 rounded hover:bg-violet-200"><X size={16} /></button>',
'          </div>',
'          <textarea value={bulkText} onChange={e => setBulkText(e.target.value)} placeholder={`RAM KUMAR\tWIDGET A\t5\t100\t18\t8471\nSITA DEVI\tSERVICE B\t1\t5000\t18\t9983`} rows={5} className={`${inputClass} font-mono text-xs`} />',
'          <div className="flex gap-2">',
'            <button onClick={parseBulk} className="px-4 py-2 rounded-lg bg-violet-500 text-white font-bold text-sm hover:bg-violet-600 transition-colors">Preview ({bulkText.trim().split("\\n").filter(l=>l.trim()).length} rows)</button>',
'            {bulkPreview.length > 0 && <button onClick={saveBulk} className="px-4 py-2 rounded-lg bg-gradient-to-r from-violet-600 to-purple-600 text-white font-bold text-sm hover:shadow-lg transition-all">Import {bulkPreview.length} Invoices</button>}',
'          </div>',
'          {bulkPreview.length > 0 && (',
'            <div className="overflow-x-auto rounded-lg border">',
'              <table className="w-full text-xs"><thead className="bg-violet-100"><tr>',
'                <th className="px-3 py-2 text-left">Party</th><th className="px-3 py-2 text-left">Item</th>',
'                <th className="px-3 py-2">Qty</th><th className="px-3 py-2">Rate</th>',
'                <th className="px-3 py-2">GST%</th><th className="px-3 py-2 text-right">Amount</th>',
'              '</tr></thead><tbody>',
'                {bulkPreview.map((b, i) => <tr key={i} className="border-b"><td className="px-3 py-1.5">{b.party}</td><td className="px-3 py-1.5">{b.item}</td><td className="px-3 py-1.5 text-center">{b.qty}</td><td className="px-3 py-1.5 text-right">{fmtINR(b.rate)}</td><td className="px-3 py-1.5 text-center">{b.gst}%</td><td className="px-3 py-1.5 text-right font-bold">{fmtINR(b.rate * b.qty)}</td></tr>)}',
'              '</tbody></table>',
'            </div>',
'          )}',
'        </div>',
'      )}',
'',
'      {/* Create Form */}',
'      {show && (',
'        <div className="bg-card rounded-2xl border-2 border-golden/30 p-5 space-y-4 shadow-lg shadow-golden/5 animate-in fade-in slide-in-from-top-2 duration-300">',
'          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">',
'            <select value={form.party_id} onChange={e => setForm(p => ({ ...p, party_id: e.target.value }))} className={inputClass}>',
'              <option value="">Select Party *</option>',
'              {filteredParties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}',
'            </select>',
'            <input value={form.invoice_no} onChange={e => setForm(p => ({ ...p, invoice_no: e.target.value }))} placeholder="Number" className={inputClass} />',
'            <input type="date" value={form.invoice_date} onChange={e => setForm(p => ({ ...p, invoice_date: e.target.value }))} className={inputClass} />',
'            <input type="date" value={form.due_date} onChange={e => setForm(p => ({ ...p, due_date: e.target.value }))} className={inputClass} />',
'          </div>',
'',
'          <div className="overflow-x-auto">',
'            <table className="w-full text-xs">',
'              <thead className="bg-muted/50"><tr>',
'                <th className="px-2 py-1.5 text-left">Item</th>',
'                <th className="px-2 py-1.5 text-left">Description</th>',
'                <th className="px-2 py-1.5">HSN</th>',
'                <th className="px-2 py-1.5">Qty</th>',
'                <th className="px-2 py-1.5">Rate</th>',
'                <th className="px-2 py-1.5">GST%</th>',
'                <th className="px-2 py-1.5 text-right">Amount</th><th></th>',
'              '</tr></thead>',
'              <tbody>',
'                {lines.map((l, i) => (',
'                  <tr key={i} className="border-b border-border/30">',
'                    <td className="px-1 py-1">',
'                      <select onChange={e => fillFromItem(i, e.target.value)} className={`${inputClass} text-xs px-2 py-1`}>',
'                        <option value="">Pick</option>',
'                        {items.map(it => <option key={it.id} value={it.id}>{it.name}</option>)}',
'                      </select>',
'                    </td>',
'                    <td className="px-1 py-1"><input value={l.description} onChange={e => updateLine(i, "description", e.target.value.toUpperCase())} className={`${inputClass} text-xs px-2 py-1 uppercase`} /></td>',
'                    <td className="px-1 py-1"><input value={l.hsn} onChange={e => updateLine(i, "hsn", e.target.value)} className={`${inputClass} text-xs px-2 py-1 w-16`} /></td>',
'                    <td className="px-1 py-1"><input type="number" value={l.qty} onChange={e => updateLine(i, "qty", Number(e.target.value))} className={`${inputClass} text-xs px-2 py-1 w-14`} /></td>',
'                    <td className="px-1 py-1"><input type="number" value={l.rate} onChange={e => updateLine(i, "rate", Number(e.target.value))} className={`${inputClass} text-xs px-2 py-1 w-20`} /></td>',
'                    <td className="px-1 py-1"><input type="number" value={l.gst_rate} onChange={e => updateLine(i, "gst_rate", Number(e.target.value))} className={`${inputClass} text-xs px-2 py-1 w-14`} /></td>',
'                    <td className="px-1 py-1 text-right tabular-nums font-bold">{fmtINR(l.qty * l.rate)}</td>',
'                    <td className="px-1 py-1"><button onClick={() => removeLine(i)} className="text-destructive p-1 hover:bg-destructive/10 rounded"><Trash2 size={12} /></button></td>',
'                  </tr>',
'                ))}',
'              '</tbody>',
'            </table>',
'          </div>',
'          <button onClick={addLine} className="text-xs text-primary font-bold hover:underline flex items-center gap-1"><Plus size={12} /> Add line</button>',
'',
'          <div className="flex flex-wrap items-end justify-between gap-3 pt-3 border-t border-border">',
'            <textarea value={form.notes} onChange={e => setForm(p => ({ ...p, notes: e.target.value }))} placeholder="Notes / terms" className={`${inputClass} max-w-sm`} rows={2} />',
'            <div className="text-sm space-y-1 bg-muted/30 rounded-lg p-3">',
'              <div className="flex justify-between gap-6"><span className="text-muted-foreground">Subtotal</span><span className="tabular-nums font-bold">{fmtINR(totals.subtotal)}</span></div>',
'              <div className="flex justify-between gap-6"><span className="text-muted-foreground">Tax</span><span className="tabular-nums font-bold">{fmtINR(totals.tax)}</span></div>',
'              <div className="flex items-center justify-between gap-6"><span className="text-muted-foreground">Discount</span><input type="number" value={form.discount} onChange={e => setForm(p => ({ ...p, discount: Number(e.target.value) }))} className="w-24 text-xs px-2 py-1 rounded border border-input bg-background text-right tabular-nums" /></div>',
'              <div className="flex justify-between gap-6 text-base pt-1 border-t"><span className="font-extrabold">Total</span><span className="tabular-nums font-extrabold text-primary">{fmtINR(totals.total)}</span></div>',
'            </div>',
'          </div>',
'          <button onClick={save} className="btn-accent w-full !py-2.5 rounded-lg text-base">Save {docType === "invoice" ? "Invoice" : "Bill"}</button>',
'        </div>',
'      )}',
'',
'      {/* Search + Filter Bar */}',
'      {list.length > 0 && (',
'        <div className="flex flex-wrap gap-2 items-center">',
'          <div className="relative flex-1 min-w-[200px]">',
'            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />',
'            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search invoice no or party..." className={`${inputClass} pl-9`} />',
'          </div>',
'          <div className="flex gap-1.5">',
'            {["all", "unpaid", "partial", "paid"].map(s => (',
'              <button key={s} onClick={() => setStatusFilter(s)} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${statusFilter === s ? "bg-primary text-primary-foreground shadow" : "bg-muted/50 text-muted-foreground hover:bg-muted"}`}>{s === "all" ? "All" : s.charAt(0).toUpperCase() + s.slice(1)}</button>',
'            ))}',
'          </div>',
'        </div>',
'      )}',
'',
'      {/* Invoice List */}',
'      <div className="bg-card rounded-2xl border-2 border-golden/20 overflow-hidden shadow-sm">',
'        {list.length === 0 ? (',
'          <div className="p-12 text-center">',
'            <div className="w-16 h-16 rounded-full bg-muted/50 flex items-center justify-center mx-auto mb-3"><FileText size={28} className="text-muted-foreground" /></div>',
'            <p className="text-muted-foreground text-sm">No {docType}s yet.</p>',
'            <p className="text-muted-foreground text-xs mt-1">Click "New {docType === "invoice" ? "Invoice" : "Bill"}" or try "Quick Bill" to get started</p>',
'          </div>',
'        ) : (',
'          <div className="overflow-x-auto">',
'            <table className="w-full text-sm">',
'              <thead className="bg-gradient-to-r from-muted/80 to-muted/40"><tr>',
'                <th className="px-3 py-2.5 text-left text-xs font-bold text-muted-foreground">No</th>',
'                <th className="px-3 py-2.5 text-left text-xs font-bold text-muted-foreground">Date</th>',
'                <th className="px-3 py-2.5 text-left text-xs font-bold text-muted-foreground">Party</th>',
'                <th className="px-3 py-2.5 text-right text-xs font-bold text-muted-foreground">Total</th>',
'                <th className="px-3 py-2.5 text-right text-xs font-bold text-muted-foreground">Due</th>',
'                <th className="px-3 py-2.5 text-center text-xs font-bold text-muted-foreground">Status</th>',
'                <th className="px-3 py-2.5 text-right text-xs font-bold text-muted-foreground">Actions</th>',
'              '</tr></thead>',
'              <tbody>',
'                {filtered.length === 0 && <tr><td colSpan={7} className="p-6 text-center text-muted-foreground text-sm">No matching invoices.</td></tr>}',
'                {filtered.map(i => (',
'                  <tr key={i.id} className="border-b border-border/30 hover:bg-muted/20 transition-colors">',
'                    <td className="px-3 py-2.5 font-mono text-xs font-bold">{i.invoice_no}</td>',
'                    <td className="px-3 py-2.5 tabular-nums text-xs text-muted-foreground">{i.invoice_date}</td>',
'                    <td className="px-3 py-2.5 font-medium">{i.acc_parties?.name || "---"}</td>',
'                    <td className="px-3 py-2.5 text-right tabular-nums font-bold">{fmtINR(i.total)}</td>',
'                    <td className="px-3 py-2.5 text-right tabular-nums text-destructive">{fmtINR(Number(i.total) - Number(i.paid))}</td>',
'                    <td className="px-3 py-2.5 text-center">',
'                      <span className={`text-xs px-2.5 py-1 rounded-full font-bold ${i.status === "paid" ? "bg-emerald-100 text-emerald-700" : i.status === "partial" ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-700"}`}>{i.status}</span>',
'                    </td>',
'                    <td className="px-3 py-2.5">',
'                      <div className="flex gap-1 justify-end">',
'                        {i.status !== "paid" && <button onClick={() => recordPayment(i)} className="text-xs px-2 py-1 rounded-lg bg-emerald-50 text-emerald-700 font-bold hover:bg-emerald-100 border border-emerald-200 transition-colors">Pay</button>}',
'                        <button onClick={() => downloadPdf(i)} className="p-1.5 rounded-lg hover:bg-blue-50 text-blue-600 transition-colors"><FileDown size={14} /></button>',
'                        <button onClick={() => sharePdf(i)} className="p-1.5 rounded-lg hover:bg-green-50 text-green-600 transition-colors"><Share2 size={14} /></button>',
'                        <button onClick={() => remove(i.id)} className="p-1.5 rounded-lg hover:bg-red-50 text-red-500 transition-colors"><Trash2 size={14} /></button>',
'                      </div>',
'                    </td>',
'                  </tr>',
'                ))}',
'              '</tbody>',
'            </table>',
'          </div>',
'        )}',
'      </div>',
'    </div>',
'  );',
'};',
'',
'export default TabInvoices;',
)

[System.IO.File]::WriteAllText($componentPath, ($lines -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "=== TabInvoices.tsx UPDATED ===" -ForegroundColor Green
Write-Host "  + Quick Bill mode (3-sec billing)"
Write-Host "  + Bulk Import (tab-separated paste)"
Write-Host "  + Stats cards (total/paid/due/overdue)"
Write-Host "  + Search + status filter"
Write-Host "  + Professional UI (gradients, rounded-2xl, animations)"