# === SCRIPT 5: Professional UI for TabSettings with Sector Selector ===
# Adds: Business sector, professional card layout, gradient header

$projectRoot = $PSScriptRoot
if (-not $projectRoot) { $projectRoot = Get-Location }
$componentPath = Join-Path $projectRoot "src\components\tracker\TabSettings.tsx"

$lines = @(
'import { useEffect, useState } from "react";',
'import { acc } from "@/lib/accounting";',
'import { toast } from "sonner";',
'import { Building2, Save, Shield, Briefcase } from "lucide-react";',
'',
'const inputClass = "w-full px-3 py-2 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary";',
'const sectors = [',
'  { value: "service", label: "Service Provider", icon: "Briefcase", desc: "Consulting, IT, professional services" },',
'  { value: "trader", label: "Trader / Dealer", icon: "Store", desc: "Buy-sell goods, wholesale, retail" },',
'  { value: "manufacturer", label: "Manufacturer", icon: "Factory", desc: "Production, manufacturing units" },',
'  { value: "professional", label: "Professional", icon: "GraduationCap", desc: "Doctor, CA, Lawyer, Architect" },',
'];',
'',
'const TabSettings = ({ userId }: { userId: string }) => {',
'  const [form, setForm] = useState({',
'    business_name: "", gstin: "", pan: "", address: "", phone: "", email: "",',
'    invoice_prefix: "INV", next_invoice_no: 1, business_sector: "service",',
'  });',
'  const [loaded, setLoaded] = useState(false);',
'',
'  useEffect(() => {',
'    (async () => {',
'      const { data } = await acc("acc_business").select("*").eq("user_id", userId).maybeSingle();',
'      if (data) setForm(prev => ({ ...prev, ...data }));',
'      setLoaded(true);',
'    })();',
'    // eslint-disable-next-line',
'  }, [userId]);',
'',
'  const save = async () => {',
'    const { error } = await acc("acc_business").upsert({ user_id: userId, ...form });',
'    if (error) toast.error(error.message);',
'    else toast.success("Business settings saved");',
'  };',
'',
'  if (!loaded) return null;',
'',
'  return (',
'    <div className="max-w-2xl mx-auto space-y-6">',
'      {/* Header */}',
'      <div className="flex items-center gap-3">',
'        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/30">',
'          <Building2 size={20} className="text-white" />',
'        </div>',
'        <div>',
'          <h3 className="text-xl font-extrabold font-display">Business Settings</h3>',
'          <p className="text-xs text-muted-foreground">These details appear on every invoice & bill PDF</p>',
'        </div>',
'      </div>',
'',
'      {/* Business Sector Selection */}',
'      <div className="bg-card rounded-2xl border-2 border-golden/30 p-5 shadow-sm">',
'        <h4 className="font-bold text-sm flex items-center gap-2 mb-4">',
'          <div className="w-6 h-6 rounded bg-amber-100 flex items-center justify-center"><Briefcase size={13} className="text-amber-700" /></div>',
'          Business Sector',
'        </h4>',
'        <div className="grid grid-cols-2 gap-3">',
'          {sectors.map(s => (',
'            <button',
'              key={s.value}',
'              onClick={() => setForm(p => ({ ...p, business_sector: s.value }))}',
'              className={`text-left p-3 rounded-xl border-2 transition-all duration-200 ${form.business_sector === s.value ? "border-primary bg-primary/5 shadow-md shadow-primary/10" : "border-border bg-muted/20 hover:border-primary/30 hover:bg-muted/40"}`}',
'            >',
'              <p className={`font-bold text-sm ${form.business_sector === s.value ? "text-primary" : ""}`}>{s.label}</p>',
'              <p className="text-xs text-muted-foreground mt-0.5">{s.desc}</p>',
'            </button>',
'          ))}',
'        </div>',
'      </div>',
'',
'      {/* Business Details */}',
'      <div className="bg-card rounded-2xl border-2 border-golden/30 p-5 shadow-sm space-y-4">',
'        <h4 className="font-bold text-sm flex items-center gap-2">',
'          <div className="w-6 h-6 rounded bg-blue-100 flex items-center justify-center"><Shield size={13} className="text-blue-700" /></div>',
'          Business Details',
'        </h4>',
'        <input value={form.business_name || ""} onChange={e => setForm(p => ({ ...p, business_name: e.target.value.toUpperCase() }))} placeholder="BUSINESS NAME" className={`${inputClass} uppercase text-lg font-bold`} />',
'        <div className="grid grid-cols-2 gap-3">',
'          <div>',
'            <label className="text-xs text-muted-foreground font-medium mb-1 block">GSTIN</label>',
'            <input value={form.gstin || ""} onChange={e => setForm(p => ({ ...p, gstin: e.target.value.toUpperCase() }))} placeholder="22AAAAA0000A1Z5" className={`${inputClass} uppercase`} />',
'          </div>',
'          <div>',
'            <label className="text-xs text-muted-foreground font-medium mb-1 block">PAN</label>',
'            <input value={form.pan || ""} onChange={e => setForm(p => ({ ...p, pan: e.target.value.toUpperCase() }))} placeholder="AAAAA0000A" className={`${inputClass} uppercase`} />',
'          </div>',
'          <div>',
'            <label className="text-xs text-muted-foreground font-medium mb-1 block">Phone</label>',
'            <input value={form.phone || ""} onChange={e => setForm(p => ({ ...p, phone: e.target.value.replace(/\D/g, "") }))} placeholder="+91 98765 43210" className={inputClass} />',
'          </div>',
'          <div>',
'            <label className="text-xs text-muted-foreground font-medium mb-1 block">Email</label>',
'            <input value={form.email || ""} onChange={e => setForm(p => ({ ...p, email: e.target.value }))} placeholder="info@business.com" className={inputClass} />',
'          </div>',
'        </div>',
'        <div>',
'          <label className="text-xs text-muted-foreground font-medium mb-1 block">Address</label>',
'          <textarea value={form.address || ""} onChange={e => setForm(p => ({ ...p, address: e.target.value }))} placeholder="Full business address" className={inputClass} rows={3} />',
'        </div>',
'      </div>',
'',
'      {/* Invoice Settings */}',
'      <div className="bg-card rounded-2xl border-2 border-golden/30 p-5 shadow-sm space-y-4">',
'        <h4 className="font-bold text-sm flex items-center gap-2">',
'          <div className="w-6 h-6 rounded bg-emerald-100 flex items-center justify-center"><Save size={13} className="text-emerald-700" /></div>',
'          Invoice Settings',
'        </h4>',
'        <div className="grid grid-cols-2 gap-3">',
'          <div>',
'            <label className="text-xs text-muted-foreground font-medium mb-1 block">Invoice Prefix</label>',
'            <input value={form.invoice_prefix || ""} onChange={e => setForm(p => ({ ...p, invoice_prefix: e.target.value.toUpperCase() }))} placeholder="INV" className={`${inputClass} uppercase`} />',
'          </div>',
'          <div>',
'            <label className="text-xs text-muted-foreground font-medium mb-1 block">Next Invoice No</label>',
'            <input type="number" value={form.next_invoice_no || 1} onChange={e => setForm(p => ({ ...p, next_invoice_no: Number(e.target.value) }))} placeholder="1" className={inputClass} />',
'          </div>',
'        </div>',
'        <button onClick={save} className="w-full bg-gradient-to-r from-primary to-indigo-600 text-white !py-3 rounded-xl font-extrabold hover:shadow-lg hover:shadow-primary/30 transition-all hover:scale-[1.01]">Save All Settings</button>',
'      </div>',
'    </div>',
'  );',
'};',
'',
'export default TabSettings;',
)

[System.IO.File]::WriteAllText($componentPath, ($lines -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "=== TabSettings.tsx UPDATED ===" -ForegroundColor Green
Write-Host "  + Business sector selector (4 sectors)"
Write-Host "  + Professional card layout with labels"
Write-Host "  + Gradient header + icons"
Write-Host "  + Save button with gradient + shadow"