import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Calculator, ChevronDown, ChevronUp, Download } from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";
import logo from "@/assets/logo.png";

const EMICalculator = () => {
  const [principal, setPrincipal] = useState(500000);
  const [rate, setRate] = useState(10.5);
  const [tenure, setTenure] = useState(36);
  const [showSchedule, setShowSchedule] = useState(false);
  const [manualPrincipal, setManualPrincipal] = useState("500000");
  const [manualRate, setManualRate] = useState("10.5");
  const [manualTenure, setManualTenure] = useState("36");

  const emi = useMemo(() => {
    const r = rate / 12 / 100;
    const n = tenure;
    if (r === 0) return principal / n;
    return (principal * r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
  }, [principal, rate, tenure]);

  const totalPayment = emi * tenure;
  const totalInterest = totalPayment - principal;

  const pieData = [
    { name: "Principal", value: Math.round(principal), color: "hsl(217, 91%, 40%)" },
    { name: "Interest", value: Math.round(totalInterest), color: "hsl(43, 96%, 56%)" },
  ];

  const schedule = useMemo(() => {
    const rows = [];
    let balance = principal;
    const r = rate / 12 / 100;
    for (let m = 1; m <= tenure; m++) {
      const interest = balance * r;
      const prinPaid = emi - interest;
      balance = Math.max(0, balance - prinPaid);
      rows.push({ month: m, emi, principal: prinPaid, interest, balance });
    }
    return rows;
  }, [principal, rate, tenure, emi]);

  const formatCurrency = (n: number) =>
    "₹" + Math.round(n).toLocaleString("en-IN");

  const syncManualPrincipal = (v: string) => {
    setManualPrincipal(v);
    const n = parseInt(v);
    if (n >= 50000 && n <= 5000000) setPrincipal(n);
  };
  const syncManualRate = (v: string) => {
    setManualRate(v);
    const n = parseFloat(v);
    if (n >= 5 && n <= 30) setRate(n);
  };
  const syncManualTenure = (v: string) => {
    setManualTenure(v);
    const n = parseInt(v);
    if (n >= 6 && n <= 72) setTenure(n);
  };

  const downloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    const rows = schedule.map(r =>
      `<tr><td>${r.month}</td><td>${formatCurrency(r.emi)}</td><td>${formatCurrency(r.principal)}</td><td>${formatCurrency(r.interest)}</td><td>${formatCurrency(r.balance)}</td></tr>`
    ).join("");
    printWindow.document.write(`<!DOCTYPE html><html><head><title>EMI Schedule - Mahajan Finance</title>
      <style>body{font-family:Arial,sans-serif;padding:20px;position:relative}
      table{width:100%;border-collapse:collapse;margin-top:20px}
      th,td{border:1px solid #ddd;padding:8px;text-align:right;font-size:12px}
      th{background:#1a56a0;color:#fff;text-align:center}
      td:first-child,th:first-child{text-align:center}
      h2{color:#1a56a0;text-align:center}
      .summary{display:flex;justify-content:space-around;margin:20px 0;padding:15px;background:#f5f5f5;border-radius:8px}
      .summary div{text-align:center}
      .summary .value{font-size:18px;font-weight:bold;color:#1a56a0}
      .watermark{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%) rotate(-30deg);font-size:60px;color:rgba(26,86,160,0.05);font-weight:bold;pointer-events:none;z-index:0;white-space:nowrap}
      .footer{text-align:center;margin-top:30px;font-size:11px;color:#888}
      </style></head><body>
      <div class="watermark">MAHAJAN FINANCE</div>
      <h2>EMI Repayment Schedule</h2>
      <p style="text-align:center;color:#888">Mahajan Finance, Insurance & Accounting Services</p>
      <div class="summary">
        <div><div>Loan Amount</div><div class="value">${formatCurrency(principal)}</div></div>
        <div><div>Interest Rate</div><div class="value">${rate}% p.a.</div></div>
        <div><div>Tenure</div><div class="value">${tenure} months</div></div>
        <div><div>Monthly EMI</div><div class="value">${formatCurrency(emi)}</div></div>
        <div><div>Total Interest</div><div class="value">${formatCurrency(totalInterest)}</div></div>
      </div>
      <table><thead><tr><th>Month</th><th>EMI</th><th>Principal</th><th>Interest</th><th>Balance</th></tr></thead><tbody>${rows}</tbody></table>
      <div class="footer">Generated by Mahajan Finance | www.mahajanfinance.com | 📞 9730540215</div>
      </body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <section className="py-16 bg-card">
      <div className="container">
        <div className="text-center mb-10">
          <motion.h2
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="section-heading hover:text-golden transition-colors cursor-default"
          >
            EMI Calculator
          </motion.h2>
          <p className="section-subheading mx-auto mt-3">Plan your loan repayment with our instant EMI calculator</p>
        </div>

        <div className="max-w-4xl mx-auto bg-background rounded-xl border-2 border-golden/20 p-6 md:p-8 shadow-sm hover:shadow-lg transition-shadow">
          {/* Logo */}
          <div className="flex justify-center mb-4">
            <img src={logo} alt="Mahajan Finance" className="h-10 opacity-20" />
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            <div className="space-y-6">
              <div>
                <div className="flex justify-between mb-2">
                  <label className="text-sm font-medium text-foreground">Loan Amount</label>
                  <input type="number" value={manualPrincipal} onChange={e => syncManualPrincipal(e.target.value)} className="w-28 text-right text-sm font-semibold text-primary tabular-nums border border-input rounded px-2 py-0.5 bg-background" />
                </div>
                <input type="range" min={50000} max={5000000} step={10000} value={principal} onChange={(e) => { setPrincipal(Number(e.target.value)); setManualPrincipal(e.target.value); }} className="w-full h-2 rounded-full appearance-none cursor-pointer bg-border accent-golden" />
                <div className="flex justify-between text-xs text-muted-foreground mt-1"><span>₹50K</span><span>₹50L</span></div>
              </div>

              <div>
                <div className="flex justify-between mb-2">
                  <label className="text-sm font-medium text-foreground">Interest Rate (p.a.)</label>
                  <input type="number" value={manualRate} onChange={e => syncManualRate(e.target.value)} step={0.5} className="w-20 text-right text-sm font-semibold text-primary tabular-nums border border-input rounded px-2 py-0.5 bg-background" />
                </div>
                <input type="range" min={5} max={30} step={0.5} value={rate} onChange={(e) => { setRate(Number(e.target.value)); setManualRate(e.target.value); }} className="w-full h-2 rounded-full appearance-none cursor-pointer bg-border accent-golden" />
                <div className="flex justify-between text-xs text-muted-foreground mt-1"><span>5%</span><span>30%</span></div>
              </div>

              <div>
                <div className="flex justify-between mb-2">
                  <label className="text-sm font-medium text-foreground">Loan Tenure (months)</label>
                  <input type="number" value={manualTenure} onChange={e => syncManualTenure(e.target.value)} className="w-16 text-right text-sm font-semibold text-primary tabular-nums border border-input rounded px-2 py-0.5 bg-background" />
                </div>
                <input type="range" min={6} max={72} step={6} value={tenure} onChange={(e) => { setTenure(Number(e.target.value)); setManualTenure(e.target.value); }} className="w-full h-2 rounded-full appearance-none cursor-pointer bg-border accent-golden" />
                <div className="flex justify-between text-xs text-muted-foreground mt-1"><span>6 mo</span><span>72 mo</span></div>
              </div>
            </div>

            <div className="flex flex-col items-center justify-center bg-primary/5 rounded-xl p-6">
              <Calculator size={32} className="text-primary mb-3" />
              <p className="text-sm text-muted-foreground mb-1">Monthly EMI</p>
              <AnimatePresence mode="wait">
                <motion.p
                  key={Math.round(emi)}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.2 }}
                  className="text-4xl font-extrabold text-primary tabular-nums font-display"
                >
                  {formatCurrency(emi)}
                </motion.p>
              </AnimatePresence>

              <div className="w-full h-40 mt-4">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={pieData} cx="50%" cy="50%" innerRadius={40} outerRadius={65} dataKey="value" paddingAngle={2}>
                      {pieData.map((entry, idx) => (
                        <Cell key={idx} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(v: number) => formatCurrency(v)} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="flex gap-4 text-xs mt-1">
                <span className="flex items-center gap-1"><span className="w-3 h-3 rounded-full bg-primary inline-block" /> Principal</span>
                <span className="flex items-center gap-1"><span className="w-3 h-3 rounded-full bg-golden inline-block" /> Interest</span>
              </div>

              <div className="mt-4 w-full space-y-2 text-sm">
                <div className="flex justify-between"><span className="text-muted-foreground">Principal</span><span className="font-semibold tabular-nums">{formatCurrency(principal)}</span></div>
                <div className="flex justify-between"><span className="text-muted-foreground">Total Interest</span><span className="font-semibold tabular-nums text-golden">{formatCurrency(totalInterest)}</span></div>
                <div className="border-t border-border pt-2 flex justify-between font-bold"><span>Total Payment</span><span className="tabular-nums">{formatCurrency(totalPayment)}</span></div>
              </div>
            </div>
          </div>

          {/* Repayment Schedule */}
          <div className="mt-6 border-2 border-golden/20 rounded-xl overflow-hidden hover:shadow-md transition-shadow">
            <button onClick={() => setShowSchedule(!showSchedule)} className="w-full flex items-center justify-between p-4 hover:bg-muted/50 transition-colors">
              <span className="font-bold font-display text-foreground flex items-center gap-2">📊 Repayment Schedule</span>
              <div className="flex items-center gap-2">
                <button
                  onClick={(e) => { e.stopPropagation(); downloadPDF(); }}
                  className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:scale-105 transition-transform"
                >
                  <Download size={14} /> Download PDF
                </button>
                {showSchedule ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
              </div>
            </button>
            {showSchedule && (
              <div className="overflow-x-auto border-t border-border max-h-96 overflow-y-auto">
                <table className="w-full text-sm">
                  <thead className="bg-primary text-primary-foreground sticky top-0">
                    <tr>
                      <th className="px-3 py-2 text-left">Month</th>
                      <th className="px-3 py-2 text-right">EMI</th>
                      <th className="px-3 py-2 text-right">Principal</th>
                      <th className="px-3 py-2 text-right">Interest</th>
                      <th className="px-3 py-2 text-right">Balance</th>
                    </tr>
                  </thead>
                  <tbody>
                    {schedule.map(row => (
                      <tr key={row.month} className="border-b border-border/50 hover:bg-muted/30">
                        <td className="px-3 py-2 font-medium">{row.month}</td>
                        <td className="px-3 py-2 text-right tabular-nums">{formatCurrency(row.emi)}</td>
                        <td className="px-3 py-2 text-right tabular-nums text-primary">{formatCurrency(row.principal)}</td>
                        <td className="px-3 py-2 text-right tabular-nums text-golden">{formatCurrency(row.interest)}</td>
                        <td className="px-3 py-2 text-right tabular-nums">{formatCurrency(row.balance)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default EMICalculator;
