// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjblfeixnwqekkraurkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqYmxmZWl4bndxZWtrcmF1cmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MTA5NTUsImV4cCI6MjA5MTQ4Njk1NX0.dJAlg6nPoKyEPkFBt08tPzTvCdG3T27DiF-af0wae-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
